version: 2
updates:
  - package-ecosystem: "gopher" # Go modules
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      go-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
